### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException in GET /password/email

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk#3470]
## Error in Faveo Community

**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /password/email**
Uncaught DaveJamesMiller\Breadcrumbs\Exception: The current route (GET /password/email/{one?}/{two?}/{three?}/{four?}/{five?}) is not named - please check routes.php for an "as" parameter in /home/siswe908/public_html/helpdesk/vendor/davejamesmiller/laravel-breadcrumbs/src/CurrentRoute.php:29
Stack trace:
#0 /home/siswe908/public_html/helpdesk/vendor/davejamesmiller/laravel-breadcrumbs/src/Manager.php(88): DaveJamesMiller\Breadcrumbs\CurrentRoute->get()
#1 /home/siswe908/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): DaveJamesMiller\Breadcrumbs\Manager->render()
#2 /home/siswe908/public_html/helpdesk/storage/framework/views/281b3a89c8aff5ff14facc6d340c70a5241cc8ec.php(215): Illuminate\Support\Facades\Facade::__callStatic('render', Array)
#3 /home/siswe908/public_html/helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/home/siswe908/...')
#4 /home/siswe908/public_html/helpdesk/vendor/laravel/framewo...

[View on Bugsnag](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5ebfa0f7ad67c80017b791e0?event_id=5ebfa0f7005b314c87ec0000&i=gh&m=ci)

## Stacktrace

    vendor/davejamesmiller/laravel-breadcrumbs/src/CurrentRoute.php:29 - [main]

[View full stacktrace](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5ebfa0f7ad67c80017b791e0?event_id=5ebfa0f7005b314c87ec0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by bhanu2217** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /jr/support/public/auth/register**](https://app.bugsnag.com/ladybird-web-solution-pvt-ltd/faveo-community/errors/5ebfa0f7ad67c80017b791e0?event_id=5f1615eb005b74f600a90000&i=gh&m=ra)
