### ISSUE TITLE
"Not answered" tab at agent panel stoped working

### ISSUE THREAD

**Issue by skullchap** [ladybirdweb/faveo-helpdesk#4238]
- Faveo Version : 1.10.7
- PHP version : 7.2.34
- Database Driver & Version : MariaDB 10.3.25
- Server specification : Debian 10, Apache

#### Description: Not answered tab at agent panel stoped working.

PHP Fatal error:  Uncaught DaveJamesMiller\\Breadcrumbs\\Exception: Breadcrumb not found with name "get-filtered-tickets" in /var/www/faveo/vendor/davejamesmiller/laravel-breadcrumbs/src/Generator.php:20\nStack trace:\n#0 /var/www/faveo/vendor/davejamesmiller/laravel-breadcrumbs/src/Generator.php(13): DaveJamesMiller\\Breadcrumbs\\Generator->call('get-filtered-ti...', Array)\n#1 /var/www/faveo/vendor/davejamesmiller/laravel-breadcrumbs/src/Manager.php(97): DaveJamesMiller\\Breadcrumbs\\Generator->generate(Array, 'get-filtered-ti...', Array)\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): DaveJamesMiller\\Breadcrumbs\\Manager->render()\n#3 /var/www/faveo/storage/framework/views/fc2bca6932387556527aa12090ea2c94cb3df3e4.php(247): Illuminate\\Support\\Facades\\Facade::__callStatic('render', Array)\n#4 /var/www/faveo/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/var/www/faveo/...')\n#5 /var/www/faveo/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php in /var/www/faveo/vendor/davejamesmiller/laravel-breadcrumbs/src/Generator.php on line 20, referer: http://it-support.local/tickets?departments[]=All&show[]=inbox

http://it-support.local/tickets?departments[]=All&show[]=inbox
http://it-support.local/tickets?last-response-by%5B0%5D=Client&show%5B%5D=inbox&departments%5B%5D=All
Links that are broken.

#### Downloaded from
- [x ] master-branch

- [ ] development-branch

- [ ] release-tag

**Comment by skullchap** [comment]
It was because of a some encoding problem. Agent entered some character in the Title using Microsoft Outlook desktop client. After deleting ticket from database (ticket_thread table), system is working properly.
