### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by CokkocZateki** [ladybirdweb/faveo-helpdesk#452]
Hi.

Im trying to install and setup Faveo-Helpdesk on my server. Im using Ubuntu 14.04 with apache2. i get to the front page `/public/step1#loaded. i click accept and get error 500 on the next page. 

Ive added the info needed in the env file however i get the below error

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)' in /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55\nStack trace:\n#0 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=127....', NULL, NULL, Array)\n#1 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)\n#2 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(61): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#3 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#4 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(O in /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php on line 55
 PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)' in /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55\nStack trace:\n#0 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=127....', NULL, NULL, Array)\n#1 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)\n#2 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(61): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#3 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#4 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(O in /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php on line 55
```

**Comment by mverma16** [comment]
Has the issue been solved?

**Comment by CokkocZateki** [comment]
i had done something wrong. so all good

**Comment by mathieu-aubin** [comment]
@CokkocZateki 
It's of good practice to tell the general public what you had done wrong... Helps other readers potentially find answers to their problems before posting.
Take that same confidence you had creating this issue and let us know

**Comment by CokkocZateki** [comment]
i had forgotten to do `sudo chown www-data:www-data /opt/faveo -R`

**Comment by mathieu-aubin** [comment]
Awesome, thanks
