### ISSUE TITLE
Setup Wizard issue: Latest release  v1.11.0 4752081 /public/step1 doesn't work. error 500

### ISSUE THREAD

**Issue by PeopleInside** [ladybirdweb/faveo-helpdesk#4699]
- Faveo Version : v1.11.0
- PHP version : 7.4
- Database Driver & Version : Mysql 5.7
- Server specification : Apache 2

#### Description:

After downloading and uploading latest source release 
https://github.com/ladybirdweb/faveo-helpdesk/releases/tag/v1.11.0

Loading faveo folder by the web browser redirect to public/step1 blank page on Firefox or error 500 in the new Edge.
Server error logs has to say: 

```
Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...',
[Tue Mar 16 17:12:34.681781 2021] [proxy_fcgi:error] [pid 110906] [client IP:59091] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)\n#1 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)\n#1 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...'
[Tue Mar 16 17:12:11.207579 2021] [proxy_fcgi:error] [pid 110906] [client IP:59062] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)\n#1 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)\n#1 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...'
[Tue Mar 16 17:11:49.348576 2021] [proxy_fcgi:error] [pid 146586] [client IP:59053] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)\n#1 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61\nStack trace:\n#0 /faveo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): PDO->prepare('select * from `...', Array)\n#1 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 /faveo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n...'
```

Setup not set, I suppose this should be asked by the Wizard but Wizard never load.
Load a blank page or error 500.

#### Steps To Reproduce:

See description.

#### Downloaded from
https://github.com/ladybirdweb/faveo-helpdesk/releases/tag/v1.11.0

Unable so to install.
Never work also trying to insert database data in database.php

**Comment by mverma16** [comment]
Hi, the current versions are not compatible and have not been tested with PHP version 7.2 or greater. We are working on providing the updates and make the system compatible with a newer version of PHP until then we recommended using the app with PHP 7.1.x.
We are working towards regularizing the updates for this repo to make the system working with updated PHP and Laravel versions.

**Comment by PeopleInside** [comment]
@mverma16 thanks for your reply.
Yes maybe also this new update doesn't support PHP 7.4 but I read:

Requirements

To run Faveo your host just needs a couple of things:

    PHP Version: 7.1+

so was think PHP 7.4 was supported.
https://www.php.net/supported-versions.php

PHP 701 is deprecated and can be dangerous.
Thanks anyway.

**Comment by bhanu2217** [comment]
Faveo Helpdesk Community v2.0.0 now supports PHP 8.1 and Mysql 8
