### ISSUE TITLE
Missing check for imap module in install

### ISSUE THREAD

**Issue by guestisp** [ladybirdweb/faveo-helpdesk#6]
Faveo needs imap module when fetching email through cron but install wizard doesn't check for that requirements

**Comment by sujit223** [comment]
we tried to keep the installation as simple as possible

**Comment by guestisp** [comment]
Yes, but without that module , faveo doesn't work properly triggering an exception

**Comment by sujit223** [comment]
Yes, Exception are there. But you need to read the documentation to use it perfectly. You have to understand that settings first before using it.
If  they want to use the cron job then they should know to set the emails according to department. But if you don't want to use the system as cron execution then you can directly use it via helptopic.

**Comment by guestisp** [comment]
I don't think that keeping an exception would be good. It should be catched properly.

**Comment by sujit223** [comment]
But there is no error. The link will be blocked unless the user activates it himself manually via settings page. Please have a look at the documentation.

**Comment by sujit223** [comment]
Please have a look there is a new version

**Comment by guestisp** [comment]
I'll try.
Any changelog ?

**Comment by guestisp** [comment]
latest version is not working at all.
Error 500 in installer's final step

```
[2015-10-23 20:30:15] production.ERROR: exception 'Illuminate\Contracts\Filesystem\FileNotFoundException' with message 'File does not exist at path /var/www/html/faveo/code/app/Http\routes.php' in /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:36
Stack trace:
#0 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(210): Illuminate\Filesystem\Filesystem->get('/var/www/html/f...')
#1 /var/www/html/faveo/code/app/Http/Controllers/Installer/helpdesk/InstallController.php(399): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#2 /var/www/html/faveo/code/app/Http/Controllers/Installer/helpdesk/InstallController.php(399): Illuminate\Support\Facades\File::get('/var/www/html/f...')
#3 [internal function]: App\Http\Controllers\Installer\helpdesk\InstallController->finalize()
#4 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#5 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('finalize', Array)
#6 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Installer\helpdesk\InstallController), Object(Illuminate\Routing\Route), 'finalize')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Installer\helpdesk\InstallController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'finalize')
#13 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'finalize')
#14 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#15 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /var/www/html/faveo/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /var/www/html/faveo/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
```

**Comment by sujit223** [comment]
I have updated the code please have a check. There was an error.

**Comment by guestisp** [comment]
I've checked, install is working again
