### ISSUE TITLE
Faveo-Helpdesk Community Edition - CLI install fails (GUI install is fine)

### ISSUE THREAD

**Issue by JedMeister** [ladybirdweb/faveo-helpdesk#8106]
- Faveo Version : 2.0.0
- PHP version : 8.1.16 (installed from deb.sury.org)
- Database Driver & Version : MariaDB 10.5.18 (from Debian repos)
- Server specification : Debian Linux - 11/Bullseye

#### Description:

When trying to install via [CLI](https://docs.faveohelpdesk.com/docs/installation/installer/cli/) the initial install command:
```
php artisan install:faveo
```
Works fine:
```
 ______                      _    _      _           _           _    
|  ____|                    | |  | |    | |         | |         | |   
| |__ __ ___   _____  ___   | |__| | ___| |_ __   __| | ___  ___| | __
|  __/ _` \ \ / / _ \/ _ \  |  __  |/ _ \ | '_ \ / _` |/ _ \/ __| |/ /
| | | (_| |\ V /  __/ (_) | | |  | |  __/ | |_) | (_| |  __/\__ \   < 
|_|  \__,_| \_/ \___|\___/  |_|  |_|\___|_| .__/ \__,_|\___||___/_|\_\
                                          | |                         
                                          |_|                         

+-----------+----------------------+
| Extension | Status               |
+-----------+----------------------+
| curl      | Loading              |
| ctype     | Loading              |
| imap      | Loading              |
| mbstring  | Loading              |
| openssl   | Loading              |
| tokenizer | Loading              |
| zip       | Loading              |
| pdo       | Loading              |
| mysqli    | Loading              |
| bcmath    | Loading              |
| iconv     | Loading              |
| XML       | Loading              |
| json      | Loading              |
| fileinfo  | Loading              |
| PHP       | PHP version supports |
+-----------+----------------------+

 Do you want to intall faveo? (yes/no) [no]:
 > yes

 Which sql engine would you like to use?:
  [0] mysql
 > 0

 Enter your sql host:
 > localhost

 Enter your database name:
 > faveo

 Enter your database username:
 > faveo

 Enter your database password (blank if not entered) []:
 > e30834b98de74598c1d5ad3d2282aeaf

 Enter your sql port (blank if not entered) []:
 > 3306

.env file has created
Preinstall has checked successfully
***********************************************
*     please run 'php artisan install:db'     *
***********************************************
```

However the next command (step 4 in the docs):
```
php artisan install:db
```
fails:
```
 Do you want to migrate tables now? (yes/no) [no]:
 > 

(faveo chroot)root@tkldev6 /# turnkey-artisan install:db

 Do you want to migrate tables now? (yes/no) [no]:
 > yes

 Would you like to install dummy data in database to test before going live? (yes/no) [no]:
 > no

   INFO  Application key set successfully.  

   INFO  Preparing database.  

  Creating migration table ............................................................................................................... 42ms DONE

   INFO  Running migrations.  

  2016_02_16_140450_create_banlist_table ................................................................................................. 31ms DONE
  2016_02_16_140450_create_canned_response_table ......................................................................................... 64ms DONE
  2016_02_16_140450_create_custom_form_fields_table ...................................................................................... 32ms DONE
  2016_02_16_140450_create_custom_forms_table ............................................................................................ 30ms DONE
  2016_02_16_140450_create_date_format_table ............................................................................................. 32ms DONE
  2016_02_16_140450_create_date_time_format_table ........................................................................................ 32ms DONE
  2016_02_16_140450_create_department_table ............................................................................................. 102ms DONE
  2016_02_16_140450_create_emails_table ................................................................................................. 173ms DONE
  2016_02_16_140450_create_group_assign_department_table ................................................................................ 102ms DONE
  2016_02_16_140450_create_groups_table .................................................................................................. 43ms DONE
  2016_02_16_140450_create_help_topic_table ............................................................................................. 231ms DONE
  2016_02_16_140450_create_kb_article_relationship_table ................................................................................. 93ms DONE
  2016_02_16_140450_create_kb_article_table .............................................................................................. 30ms DONE
  2016_02_16_140450_create_kb_category_table ............................................................................................. 31ms DONE
  2016_02_16_140450_create_kb_comment_table .............................................................................................. 65ms DONE
  2016_02_16_140450_create_kb_pages_table ................................................................................................ 32ms DONE
  2016_02_16_140450_create_kb_settings_table ............................................................................................. 32ms DONE
  2016_02_16_140450_create_languages_table ............................................................................................... 33ms DONE
  2016_02_16_140450_create_log_notification_table ........................................................................................ 32ms DONE
  2016_02_16_140450_create_mailbox_protocol_table ........................................................................................ 31ms DONE
  2016_02_16_140450_create_organization_table ............................................................................................ 64ms DONE
  2016_02_16_140450_create_password_resets_table ........................................................................................ 106ms DONE
  2016_02_16_140450_create_plugins_table ................................................................................................. 30ms DONE
  2016_02_16_140450_create_settings_alert_notice_table ................................................................................... 43ms DONE
  2016_02_16_140450_create_settings_auto_response_table .................................................................................. 33ms DONE
  2016_02_16_140450_create_settings_company_table ........................................................................................ 32ms DONE
  2016_02_16_140450_create_settings_email_table .......................................................................................... 32ms DONE
  2016_02_16_140450_create_settings_ratings_table ........................................................................................ 66ms DONE
  2016_02_16_140450_create_settings_system_table ........................................................................................ 166ms DONE
  2016_02_16_140450_create_settings_ticket_table ......................................................................................... 35ms DONE
  2016_02_16_140450_create_sla_plan_table ................................................................................................ 32ms DONE
  2016_02_16_140450_create_team_assign_agent_table ....................................................................................... 96ms DONE
  2016_02_16_140450_create_teams_table ................................................................................................... 65ms DONE
  2016_02_16_140450_create_template_table ................................................................................................ 31ms DONE
  2016_02_16_140450_create_ticket_attachment_table ....................................................................................... 96ms DONE
  2016_02_16_140450_create_ticket_collaborator_table .................................................................................... 108ms DONE
  2016_02_16_140450_create_ticket_form_data_table ........................................................................................ 65ms DONE
  2016_02_16_140450_create_ticket_priority_table ......................................................................................... 33ms DONE
  2016_02_16_140450_create_ticket_source_table ........................................................................................... 30ms DONE
  2016_02_16_140450_create_ticket_status_table ........................................................................................... 31ms DONE
  2016_02_16_140450_create_ticket_thread_table .......................................................................................... 193ms DONE
  2016_02_16_140450_create_tickets_table ................................................................................................ 440ms DONE
  2016_02_16_140450_create_time_format_table ............................................................................................. 59ms DONE
  2016_02_16_140450_create_timezone_table ................................................................................................ 52ms DONE
  2016_02_16_140450_create_user_assign_organization_table ............................................................................... 165ms DONE
  2016_02_16_140450_create_users_table .................................................................................................. 267ms DONE
  2016_02_16_140450_create_version_check_table ........................................................................................... 52ms DONE
  2016_02_16_140450_create_widgets_table ................................................................................................. 49ms DONE
  2016_02_16_140454_add_foreign_keys_to_canned_response_table ........................................................................... 140ms DONE
  2016_02_16_140454_add_foreign_keys_to_department_table ................................................................................ 318ms DONE
  2016_02_16_140454_add_foreign_keys_to_emails_table .................................................................................... 624ms DONE
  2016_02_16_140454_add_foreign_keys_to_group_assign_department_table ................................................................... 309ms DONE
  2016_02_16_140454_add_foreign_keys_to_help_topic_table .............................................................................. 1,174ms DONE
  2016_02_16_140454_add_foreign_keys_to_kb_article_relationship_table ................................................................... 317ms DONE
  2016_02_16_140454_add_foreign_keys_to_kb_comment_table ................................................................................ 146ms DONE
  2016_02_16_140454_add_foreign_keys_to_organization_table .............................................................................. 445ms DONE
  2016_02_16_140454_add_foreign_keys_to_settings_system_table ......................................................................... 1,073ms DONE
  2016_02_16_140454_add_foreign_keys_to_team_assign_agent_table ......................................................................... 222ms DONE
  2016_02_16_140454_add_foreign_keys_to_teams_table ...................................................................................... 97ms DONE
  2016_02_16_140454_add_foreign_keys_to_ticket_attachment_table .......................................................................... 92ms DONE
  2016_02_16_140454_add_foreign_keys_to_ticket_collaborator_table ....................................................................... 204ms DONE
  2016_02_16_140454_add_foreign_keys_to_ticket_form_data_table ........................................................................... 96ms DONE
  2016_02_16_140454_add_foreign_keys_to_ticket_thread_table ............................................................................. 346ms DONE
  2016_02_16_140454_add_foreign_keys_to_tickets_table ................................................................................. 1,455ms DONE
  2016_02_16_140454_add_foreign_keys_to_user_assign_organization_table .................................................................. 210ms DONE
  2016_02_16_140454_add_foreign_keys_to_users_table ..................................................................................... 250ms DONE
  2016_03_31_061239_create_notifications_table ........................................................................................... 30ms DONE
  2016_03_31_061534_create_notification_types_table ...................................................................................... 43ms DONE
  2016_03_31_061740_create_user_notification_table ....................................................................................... 48ms DONE
  2016_04_18_115852_create_workflow_name_table ........................................................................................... 31ms DONE
  2016_04_18_115900_create_workflow_rule_table .......................................................................................... 123ms DONE
  2016_04_18_115908_create_workflow_action_table ........................................................................................ 122ms DONE
  2016_05_10_102423_create_country_code_table ............................................................................................ 30ms DONE
  2016_05_10_102604_create_bar_notifications_table ....................................................................................... 31ms DONE
  2016_05_11_105244_create_api_settings_table ............................................................................................ 31ms DONE
  2016_05_19_055008_create_workflow_close_table .......................................................................................... 44ms DONE
  2016_06_02_072210_create_common_settings_table ......................................................................................... 31ms DONE
  2016_06_02_074913_create_login_attempts_table .......................................................................................... 31ms DONE
  2016_06_02_080005_create_ratings_table ................................................................................................. 31ms DONE
  2016_06_02_081020_create_rating_ref_table .............................................................................................. 29ms DONE
  2016_06_02_090225_create_settings_security_table ....................................................................................... 31ms DONE
  2016_06_02_090628_create_templates_table ............................................................................................... 31ms DONE
  2016_06_02_094409_create_template_sets_table ........................................................................................... 30ms DONE
  2016_06_02_094420_create_template_types_table .......................................................................................... 30ms DONE
  2016_06_02_095357_create_ticket_token_table ............................................................................................ 32ms DONE
  2016_06_28_141613_version1079table ..................................................................................................... 13ms DONE
  2016_07_02_051247_create_jobs_table .................................................................................................... 72ms DONE
  2016_07_02_051439_create_failed_jobs_table ............................................................................................. 31ms DONE
  2016_07_19_071910_create_field_values_table ........................................................................................... 129ms DONE
  2016_07_26_084458_create_faveo_mails_table ............................................................................................. 31ms DONE
  2016_07_26_090201_create_faveo_queues_table ............................................................................................ 35ms DONE
  2016_07_26_094753_create_mail_services_table ........................................................................................... 31ms DONE
  2016_07_26_095020_create_queue_services_table .......................................................................................... 31ms DONE
  2016_07_29_113012_create_conditions_table .............................................................................................. 31ms DONE
  2016_08_08_095744_create_social_media_table ............................................................................................ 30ms DONE
  2016_08_12_104410_create_user_additional_infos_table ................................................................................... 30ms DONE
  2016_08_16_104539_alter_ticket_source_table ............................................................................................ 18ms DONE
  2018_08_08_094653_alter_users_table_add_user_language_column ........................................................................... 18ms DONE
  2018_08_13_075015_alter_emails_table_make_username_column_nullable .................................................................... 125ms DONE
  2023_01_07_000000_add_uuid_to_failed_jobs_table ........................................................................................ 63ms DONE

Migrated successfully
   INFO  Seeding database.  

Target class [DatabaseSeeder] does not exist.
```

If I try to browse to Faveo (i.e. in a web browser) it just displays a blank white page and there is an error logged (to the Apache log file - `/var/log/apache2/error.log`):
```
[Wed Mar 15 19:11:16.982440 2023] [php:error] [pid 3204608] [client 192.168.1.56:43864] PHP Fatal error:  Uncaught ErrorException: Attempt to read property "url" on null in /var/www/faveo-helpdesk/storage/framework/views/65efd5d0e8e71f0ec31906e0b29cd7666da86c74.php:100\nStack trace:\n#0 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/faveo-helpdesk/storage/framework/views/65efd5d0e8e71f0ec31906e0b29cd7666da86c74.php(100): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#2 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')\n#3 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#4 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#5 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#6 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#7 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#8 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#9 /var/www/faveo-helpdesk/storage/framework/views/e7238cc62c1e7c72907e0af629ce03310a4d870b.php(19): Illuminate\\View\\View->render()\n#10 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')\n#11 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#12 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#13 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#14 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#15 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#16 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#17 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#18 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#19 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#20 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#21 /var/www/faveo-helpdesk/app/Exceptions/Handler.php(118): Illuminate\\Routing\\ResponseFactory->view()\n#22 /var/www/faveo-helpdesk/app/Exceptions/Handler.php(213): App\\Exceptions\\Handler->render500()\n#23 /var/www/faveo-helpdesk/app/Exceptions/Handler.php(88): App\\Exceptions\\Handler->common()\n#24 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\\Exceptions\\Handler->render()\n#25 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#26 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(242): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#27 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#28 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#29 {main}\n\nNext Illuminate\\View\\ViewException: Attempt to read property "url" on null (View: /var/www/faveo-helpdesk/resources/views/themes/default1/client/layout/client.blade.php) in /var/www/faveo-helpdesk/storage/framework/views/65efd5d0e8e71f0ec31906e0b29cd7666da86c74.php:100\nStack trace:\n#0 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()\n#1 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#2 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#3 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#4 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#5 /var/www/faveo-helpdesk/storage/framework/views/e7238cc62c1e7c72907e0af629ce03310a4d870b.php(19): Illuminate\\View\\View->render()\n#6 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')\n#7 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#8 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#9 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#10 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#11 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#12 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#13 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#14 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#15 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#16 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#17 /var/www/faveo-helpdesk/app/Exceptions/Handler.php(118): Illuminate\\Routing\\ResponseFactory->view()\n#18 /var/www/faveo-helpdesk/app/Exceptions/Handler.php(213): App\\Exceptions\\Handler->render500()\n#19 /var/www/faveo-helpdesk/app/Exceptions/Handler.php(88): App\\Exceptions\\Handler->common()\n#20 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\\Exceptions\\Handler->render()\n#21 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#22 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(242): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#23 /var/www/faveo-helpdesk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\
```

If I start again from the start and re-run the steps via the GUI (in a web browser) it appears to work fine!?

#### Steps To Reproduce:

As noted above.

#### Downloaded from

- [x] release-tag

**Comment by JedMeister** [comment]
Out of interest, I fired up a clean Debian 11 and tried installing via the [install script](https://docs.faveohelpdesk.com/docs/installation/providers/enterprise/script-installers/). That doesn't work either, although I suspect that the issue is different. The script completes successfully but when I try to browse to Faveo, I get a "403 Forbidden" error. In the apache log:
```
[Wed Mar 15 20:41:50.573240 2023] [autoindex:error] [pid 49631] [client 192.168.1.56:48262] AH01276: Cannot serve directory /var/www/faveo/public/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
```

And if I look in that directory there is only a `test.php` file:
```
root@JED-TEST-faveo-install-sh ~# ls -la /var/www/faveo/public/          
total 12
drwxr-xr-x 2 www-data www-data 4096 Mar 15 20:37 .
drwxr-xr-x 3 www-data www-data 4096 Mar 15 20:37 ..
-rw-r--r-- 1 www-data www-data    5 Mar 15 20:37 test.html
```

I assume that this is unrelated to my initial bug report, but figured I may as well share.
