### ISSUE TITLE
Installed unable to load after configureing DB

### ISSUE THREAD

**Issue by robbiesahn** [ladybirdweb/faveo-helpdesk#8307]
- Faveo Version : latest version
- Product Name : Faveo Freeancer
- PHP version : PHP 8.2
- Database Driver & Version : Mysql 8 
- Server specification : ubuntu 22

#### Description:
Unable to get the page to come up after Completing GUI Install

#### Steps To Reproduce:
Installed follow exact procedures. Once attempting to load after completing GUI install I get a 500 error
 [php:error] [pid 67573:tid 67573] [client 192.168.1.*:56805] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#5 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[Wed Dec 25 06:28:18.495429 2024] [php:error] [pid 67573:tid 67573] [client 192.168.1.*:56805] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#5 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#6 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[Thu Dec 26 05:48:25.482315 2024] [php:error] [pid 67575:tid 67575] [client 192.168.1.*:55142] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#5 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[Thu Dec 26 05:48:25.482941 2024] [php:error] [pid 67575:tid 67575] [client 192.168.1.*:55142] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#5 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#6 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[Thu Dec 26 05:48:31.850882 2024] [php:error] [pid 67595:tid 67595] [client 192.168.1.*:55147] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#5 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[Thu Dec 26 05:48:31.851438 2024] [php:error] [pid 67595:tid 67595] [client 192.168.1.*:55147] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#5 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#6 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[Thu Dec 26 05:50:35.418878 2024] [php:error] [pid 67583:tid 67583] [client 192.168.1.*:55189] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#5 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355, referer:
[Thu Dec 26 05:50:35.419584 2024] [php:error] [pid 67583:tid 67583] [client 192.168.1.*:55189] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#5 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#6 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355, referer: 
[Thu Dec 26 05:50:52.657765 2024] [php:error] [pid 78366:tid 78366] [client 192.168.1.*:55193] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#5 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355, referer:
[Thu Dec 26 05:50:52.658748 2024] [php:error] [pid 78366:tid 78366] [client 192.168.1.*:55193] PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag::notifyException() in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:355\nStack trace:\n#0 /var/www/faveo/app/Exceptions/Handler.php(193): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#1 /var/www/faveo/app/Exceptions/Handler.php(71): App\\Exceptions\\Handler->reportToBugsnag()\n#2 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(183): App\\Exceptions\\Handler->report()\n#3 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#4 /var/www/faveo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#5 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#6 {main}\n  thrown in /var/www/faveo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355,

#### Downloaded from
- [ ] master-branch

- [ ] development-branch

- [X ] release-tag

**Comment by robbiesahn** [comment]
so apparently this was user error. I redownloaded the zip file and extracted it to my server. then went through the installation again. This time it is working so chalk up to user error
